/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/components/butondone.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/butondone.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.202, 1.219, -0.795]} scale={0.147}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/butondone.glb')
