/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/components/mesa.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MESA(props) {
  const { nodes, materials } = useGLTF('public/components/mesa.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.09, 0]} scale={[2.345, 0.089, 1.735]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('public/components/mesa.glb')
